import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  headerTitle: {
    fontSize: typography.h3,
    fontWeight: '700',
    color: colors.ink,
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  title: {
    fontSize: typography.h1,
    fontWeight: '800',
    color: colors.ink,
  },
  subtitle: {
    marginTop: 4,
    fontSize: typography.body,
    color: colors.muted,
  },
  receiptWrap: {
    marginTop: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  receiptImage: {
    width: '100%',
    height: 200,
  },
  sectionCard: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  sectionTitle: {
    fontSize: typography.h3,
    fontWeight: '700',
    color: colors.ink,
  },
  label: {
    fontSize: typography.small,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: colors.muted,
    marginTop: spacing.md,
  },
  input: {
    marginTop: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    fontSize: typography.body,
    color: colors.ink,
    backgroundColor: '#FFFCF8',
  },
  textArea: {
    height: 90,
    textAlignVertical: 'top',
  },
  categoryRow: {
    marginTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  categoryChip: {
    marginRight: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFFCF8',
  },
  categoryChipActive: {
    backgroundColor: '#FFF3DB',
    borderColor: colors.accent,
  },
  categoryChipText: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  dateButton: {
    marginTop: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    backgroundColor: '#FFFCF8',
  },
  dateText: {
    fontSize: typography.body,
    color: colors.ink,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.lg,
  },
  deleteButton: {
    flex: 1,
    marginRight: spacing.sm,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.danger,
    alignItems: 'center',
  },
  deleteText: {
    color: colors.danger,
    fontWeight: '700',
    fontSize: typography.small,
  },
  saveButton: {
    flex: 1,
    marginLeft: spacing.sm,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.ink,
    alignItems: 'center',
  },
  saveText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: typography.small,
  },
  itemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    backgroundColor: '#FFFCF8',
  },
  addItemText: {
    marginLeft: 4,
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  itemsList: {
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    overflow: 'hidden',
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#FFFCF8',
  },
  itemLeft: {
    flex: 1,
  },
  itemName: {
    flex: 1,
    fontSize: typography.body,
    color: colors.ink,
  },
  itemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemCategory: {
    marginTop: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFF3DB',
  },
  itemCategoryText: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  itemPrice: {
    fontSize: typography.body,
    fontWeight: '700',
    color: colors.ink,
    marginRight: spacing.sm,
  },
  itemDelete: {
    padding: 4,
  },
  mutedText: {
    marginTop: spacing.sm,
    fontSize: typography.small,
    color: colors.muted,
  },
  splitSummary: {
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFFCF8',
  },
  splitTitle: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  splitRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
  },
  splitLabel: {
    fontSize: typography.small,
    color: colors.muted,
  },
  splitValue: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  sheetCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: spacing.lg,
    borderTopWidth: 1,
    borderColor: colors.border,
    maxHeight: '70%',
  },
  sheetHandle: {
    width: 46,
    height: 5,
    borderRadius: 999,
    alignSelf: 'center',
    backgroundColor: colors.border,
    marginBottom: spacing.md,
  },
  sheetTitle: {
    fontSize: typography.h3,
    fontWeight: '700',
    color: colors.ink,
    marginBottom: spacing.md,
  },
  sheetList: {
    maxHeight: 320,
  },
  sheetOption: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sheetOptionActive: {
    backgroundColor: '#FFF3DB',
  },
  sheetOptionText: {
    fontSize: typography.body,
    fontWeight: '600',
    color: colors.ink,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    fontSize: typography.h3,
    fontWeight: '800',
    color: colors.ink,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.lg,
  },
  cancelButton: {
    flex: 1,
    marginRight: spacing.sm,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  cancelText: {
    color: colors.muted,
    fontWeight: '600',
    fontSize: typography.small,
  },
  missing: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  backButton: {
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  backText: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
});
