import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: typography.body,
    color: colors.muted,
  },
  title: {
    fontSize: typography.h1,
    fontWeight: '800',
    color: colors.ink,
  },
  subtitle: {
    marginTop: 4,
    fontSize: typography.body,
    color: colors.muted,
  },
  card: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  label: {
    fontSize: typography.small,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: colors.muted,
    marginTop: spacing.md,
  },
  input: {
    marginTop: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    fontSize: typography.body,
    color: colors.ink,
    backgroundColor: '#FFFCF8',
  },
  dateButton: {
    marginTop: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    backgroundColor: '#FFFCF8',
  },
  dateText: {
    fontSize: typography.body,
    color: colors.ink,
  },
  textArea: {
    height: 90,
    textAlignVertical: 'top',
  },
  pills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing.sm,
  },
  cta: {
    marginTop: spacing.lg,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: colors.ink,
    alignItems: 'center',
  },
  ctaText: {
    color: '#fff',
    fontSize: typography.body,
    fontWeight: '700',
  },
  photoCard: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  photoTitle: {
    fontSize: typography.body,
    fontWeight: '700',
    color: colors.ink,
  },
  photoHint: {
    marginTop: spacing.xs,
    fontSize: typography.small,
    color: colors.muted,
  },
  photoButton: {
    marginTop: spacing.md,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  photoButtonText: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  ocrHint: {
    marginTop: spacing.sm,
    fontSize: typography.small,
    color: colors.muted,
  },
  previewWrap: {
    marginTop: spacing.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  preview: {
    width: '100%',
    height: 160,
  },
  removePreview: {
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFF3DB',
  },
  removePreviewText: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  debugCard: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFF8EC',
  },
  debugTitle: {
    fontSize: typography.body,
    fontWeight: '700',
    color: colors.ink,
  },
  debugText: {
    marginTop: spacing.sm,
    fontSize: typography.small,
    color: colors.muted,
  },
  debugButton: {
    marginTop: spacing.md,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    backgroundColor: '#FFFCF8',
  },
  debugButtonText: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  debugLink: {
    marginTop: spacing.sm,
    alignItems: 'center',
  },
  debugLinkText: {
    fontSize: typography.small,
    color: colors.ink,
    fontWeight: '700',
  },
  itemsCard: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  itemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemsTitle: {
    fontSize: typography.body,
    fontWeight: '700',
    color: colors.ink,
  },
  itemsAdd: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    backgroundColor: '#FFFCF8',
  },
  itemsAddText: {
    marginLeft: 4,
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  itemsList: {
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    overflow: 'hidden',
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: '#FFFCF8',
  },
  itemName: {
    flex: 1,
    fontSize: typography.body,
    color: colors.ink,
  },
  itemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemPrice: {
    fontSize: typography.body,
    fontWeight: '700',
    color: colors.ink,
    marginRight: spacing.sm,
  },
  itemDelete: {
    padding: 4,
  },
  itemsEmpty: {
    marginTop: spacing.sm,
    fontSize: typography.small,
    color: colors.muted,
  },
  reconcileCard: {
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFFCF8',
  },
  reconcileTitle: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  reconcileText: {
    marginTop: 4,
    fontSize: typography.small,
    color: colors.muted,
  },
  reconcileWarn: {
    marginTop: spacing.xs,
    fontSize: typography.small,
    color: colors.danger,
    fontWeight: '700',
  },
  reconcileActions: {
    flexDirection: 'row',
    marginTop: spacing.sm,
  },
  reconcileButton: {
    flex: 1,
    marginRight: spacing.sm,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    backgroundColor: '#FFF3DB',
  },
  reconcileButtonText: {
    fontSize: typography.small,
    fontWeight: '700',
    color: colors.ink,
  },
  reconcileButtonDisabled: {
    opacity: 0.4,
  },
  reconcileHint: {
    marginTop: spacing.xs,
    fontSize: typography.small,
    color: colors.muted,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    fontSize: typography.h3,
    fontWeight: '800',
    color: colors.ink,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.lg,
  },
  modalCancel: {
    flex: 1,
    marginRight: spacing.sm,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  modalCancelText: {
    color: colors.muted,
    fontWeight: '600',
    fontSize: typography.small,
  },
  modalSave: {
    flex: 1,
    marginLeft: spacing.sm,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.ink,
    alignItems: 'center',
  },
  modalSaveText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: typography.small,
  },
});

